// This file is auto-generated by the Web Hatchery standard boilerplate

// ============================================================================
// Runtime Exports (As required by standards-frontend.md)
// ============================================================================

/**
 * Standard API Response Wrapper
 */
export class ApiResponse<T = unknown> {
    success!: boolean;
    data?: T;
    error?: string;

    constructor(init?: Partial<ApiResponse<T>>) {
        Object.assign(this, init);
    }
}

/**
 * Standard API Error Class
 */
export class ApiError extends Error {
    public status: number;

    constructor(message: string, status: number = 500) {
        super(message);
        this.name = 'ApiError';
        this.status = status;
    }
}
